### ISSUE TITLE
SR not working after Qnap upgrade

### ISSUE THREAD

**Issue by Dohnerd** [SickChill/qnap-sickchill#2]
Ok heres the deal, yesterday i updatede my QNAP and wanted to install the QSickRage_1.1_x86__20160410.qpkg, it installs fine, but it dosn't run:

[/share/CACHEDEV1_DATA/.qpkg/QSickRage] # ./QSickRage.sh restart
Restarting QSickRage
Shutting down QSickRage...
QSickRage is not running?
QSickRage prestartup checks...
 Checking for git...Git Found!
Looking for /usr/bin/python2.7
Looking for /usr/local/bin/python2.7
Looking for /opt/bin/python2.7
Looking for /Apps/opt/bin/python2.7
Looking for /opt/QPython2/bin/python2.7
Found Python Version 2.7.5 at /usr/local/bin/python2.7
Updating QSickRage
HEAD is now at 7111172 Update torrentproject to use api magnet (#1632)
Already up-to-date.
Starting QSickRage
Traceback (most recent call last):
  File "SickBeard.py", line 94, in <module>
    import sickbeard
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage/sickbeard/**init**.py", line 37, in <module>
    from sickbeard import metadata
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage/sickbeard/metadata/**init**.py", line 22, in <module>
    from sickbeard.metadata import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er, generic, helpers
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage/sickbeard/metadata/kodi.py", line 23, in <module>
    from sickbeard.metadata import generic
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage/sickbeard/metadata/generic.py", line 32, in <module>
    from sickbeard import helpers
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage/sickbeard/helpers.py", line 33, in <module>
    from requests.utils import urlparse
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage/lib/requests/**init**.py", line 58, in <module>
    from . import utils
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage/lib/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage/lib/requests/compat.py", line 39, in <module>
    import cookielib
ImportError: No module named cookielib

Help pls......

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked
- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Dohnerd** [comment]
ok so i noticed SR was using 2.7.5, the /usr/local/bin/python2.7, forced it to use 2.7.9 in /opt/QPython2/bin/python2.7... and reinstalled qpkg... now it works again :)
