### ISSUE TITLE
ImportError: No module named ast

### ISSUE THREAD

**Issue by zeon** [SickChill/qnap-sickchill#4]
Hi There,

I tried to install the qpkg onto my NAS but it keeps giving this error:

[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage] # ./sickbeard-tvrage.sh restart
x86_64
Restarting SickBeard-TVRage
x86_64
Shutting down SickBeard-TVRage...
SickBeard-TVRage is not running?
x86_64
SickBeard-TVRage prestartup checks...
 Checking for git...  Found!
Looking for /usr/bin/python2.7
Looking for /usr/local/bin/python2.7
Looking for /opt/bin/python2.7
Looking for /Apps/opt/bin/python2.7
Looking for /opt/QPython2/bin/python2.7
Found Python Version 2.7.13 at /opt/QPython2/bin/python2.7
Updating SickBeard-TVRage
HEAD is now at 87e5ce8 Fix anime episode search (part 3)
Already up-to-date.
Starting SickBeard-TVRage
Traceback (most recent call last):
  File "SickBeard.py", line 65, in <module>
    import sickbeard
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/__init__.py", line 37, in <module>
    from sickbeard.indexers import indexer_api
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/indexers/__init__.py", line 21, in <module>
    from . import indexer_api
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/indexers/indexer_api.py", line 26, in <module>
    from indexer_config import initConfig
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/indexers/indexer_config.py", line 4, in <module>
    from sickbeard import helpers
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 24, in <module>
    import ast
ImportError: No module named ast

Do you have any idea what this is about? Thanks very much

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
